In [1]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v1')

In [5]:
env.observation_space.n

16

In [9]:
env.action_space.n

4

In [10]:
Q = np.zeros([env.observation_space.n,env.action_space.n])

In [12]:
lr = .8
y = .95
num_episodes = 2000

In [13]:
rList = []

In [14]:
s = env.reset()
print(s)

(0, {'prob': 1})


In [19]:
a = np.argmax(Q[s[0],:] + np.random.randn(1,env.action_space.n)*(1./(0+1)))

In [15]:
np.random.randn(1,env.action_space.n)

array([[-1.55081319,  1.19731718, -0.91767436,  2.00721777]])

In [25]:
Q[s[0],:]

array([0., 0., 0., 0.])

In [27]:
env.step(a)

(1, 0.0, False, False, {'prob': 0.3333333333333333})

In [28]:
env.desc

array([[b'S', b'F', b'F', b'F'],
       [b'F', b'H', b'F', b'H'],
       [b'F', b'F', b'F', b'H'],
       [b'H', b'F', b'F', b'G']], dtype='|S1')

In [30]:
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()[0]
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [31]:
Q

array([[4.72322083e-02, 3.81796400e-03, 4.27323816e-03, 0.00000000e+00],
       [3.51423141e-03, 3.26875176e-04, 7.34734919e-05, 7.58064297e-02],
       [1.99157092e-03, 1.05130728e-01, 2.75802810e-03, 4.28287681e-03],
       [8.72325295e-04, 9.05547519e-04, 9.97591587e-06, 7.35377823e-02],
       [4.57758532e-02, 4.42616963e-03, 6.01036192e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.60473435e-02, 3.59682601e-06, 5.63011461e-04, 5.86334580e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.41476529e-03, 1.07661373e-01],
       [1.66312986e-03, 1.61992960e-01, 1.63887737e-03, 0.00000000e+00],
       [1.10267259e-01, 3.52642868e-04, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.78390550e

In [33]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4065
